services:
  web-app:
    build: 
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./config:/config
    environment:
      - DB_HOST=database
      - DB_NAME=oracle
      - DB_USER=altai
      - DB_PASS=1

    command: >
      sh -c "python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=oracle
      - POSTGRES_USER=altai
      - POSTGRES_PASSWORD=1